server:
  port: 8080

jwt:
  signerKey: "qUZg3QK6XUc8M6ydXOoEGekDIOEDNhlFqlFm7GdiqXus9EgqwzvBPEOI+fATDHZI"
  valid-duration: 36000  # Thời gian hết hạn token (giây)
  refresh-duration: 36000  # Thời gian hết hạn refresh token (giây)

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2025letmecook@gmail.com
    password: xgpryoziwthfiude
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  datasource:
    url: "jdbc:mysql://localhost:3306/appnauan"
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

      ddl-auto=update:show-sql: true

      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Cấu hình upload file
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB     # Tăng giới hạn file tối đa lên 50MB
      max-request-size: 50MB  # Tăng giới hạn request tối đa lên 50MB
      file-size-threshold: 1MB  # File lớn hơn 1MB sẽ được ghi tạm vào đĩa

cloudinary:
  cloud_name: dcvejqvlp
  api_key: 387319119399615
  api_secret: cXnMf-xXOJ_ncRZDw7O4vFiBi-4

logging:
  level:
    com.example.letmecookbe.service.EmailVerification: DEBUG
    com.example.letmecookbe.service.AccountService: DEBUG
    com.example.letmecookbe.service.FileStorageService: DEBUG

google:
  client-id: 810762213774-9pdqiru4ct3s03r42phjulqqqksf89ru.apps.googleusercontent.com